// Component specifications shown in the inspection panel.
// Sources: manufacturer product pages / datasheets (see README).
export const SPECS = {
	cpu: {
		kicker: 'Processor',
		name: 'AMD Ryzen 5 7500F',
		specs: [
			[ 'Architecture', 'Zen 4, 5 nm (TSMC)' ],
			[ 'Cores / threads', '6 / 12' ],
			[ 'Base / boost clock', '3.7 GHz / up to 5.0 GHz' ],
			[ 'L2 / L3 cache', '6 MB / 32 MB' ],
			[ 'Default TDP', '65 W' ],
			[ 'Socket', 'AM5 (LGA 1718)' ],
			[ 'Memory', 'DDR5, dual channel' ],
			[ 'Graphics', 'None (iGPU disabled "F" SKU)' ],
		],
		note: 'Mounted under the DeepCool LQ360 pump — open the exploded view to reveal the heat spreader.',
	},
	gpu: {
		kicker: 'Graphics card',
		name: 'ASUS PRIME Radeon RX 9060 XT OC 16GB',
		specs: [
			[ 'GPU', 'AMD Navi 44 (RDNA 4), 32 CUs' ],
			[ 'Memory', '16 GB GDDR6, 128-bit, 20 Gbps' ],
			[ 'Boost clock', 'up to 3330 MHz (OC mode) / 3310 MHz (default)' ],
			[ 'Game clock', '2760 MHz (OC mode)' ],
			[ 'Interface', 'PCIe 5.0 x16' ],
			[ 'Dimensions', '304 × 126 × 50 mm, 2.5-slot' ],
			[ 'Cooling', '3 × Axial-tech fans, 0 dB below 55 °C' ],
			[ 'Power', '1 × 8-pin, 550 W PSU recommended' ],
			[ 'Outputs', '1 × HDMI 2.1b, 2 × DisplayPort 2.1a' ],
		],
	},
	motherboard: {
		kicker: 'Motherboard',
		name: 'MSI MPG B850 EDGE TI WIFI',
		specs: [
			[ 'Chipset / socket', 'AMD B850 / AM5' ],
			[ 'Form factor', 'ATX, 305 × 244 mm' ],
			[ 'Memory', '4 × DDR5 DIMM, up to 8400+ MT/s (OC)' ],
			[ 'Expansion', 'PCIe 5.0 x16, PCIe 4.0 x16 (x4), PCIe 3.0 x1' ],
			[ 'Storage', '4 × M.2 (2 × Gen5 x4, Gen4 x4, Gen4 x2)' ],
			[ 'VRM', '14+2+1 phases, 80 A smart power stages' ],
			[ 'Networking', 'Wi-Fi 7, Bluetooth 5.4, Realtek 5 GbE' ],
			[ 'Design', 'Silver-white, M.2 Shield Frozr, 8-layer PCB' ],
		],
	},
	ram: {
		kicker: 'Memory',
		name: 'Kingston FURY Beast RGB DDR5-6000 CL30',
		specs: [
			[ 'Capacity', '32 GB kit (2 × 16 GB)' ],
			[ 'Speed / latency', '6000 MT/s, CL30' ],
			[ 'Profiles', 'AMD EXPO / Intel XMP 3.0' ],
			[ 'Voltage', '1.40 V (EXPO profile)' ],
			[ 'Height', '42.2 mm' ],
			[ 'Lighting', 'RGB light bar, Kingston FURY Infrared Sync' ],
			[ 'Installed slots', 'DIMMA2 + DIMMB2 (dual channel)' ],
		],
	},
	ssd: {
		kicker: 'Storage',
		name: 'Lexar NM790 1TB NVMe',
		specs: [
			[ 'Interface', 'PCIe 4.0 x4, NVMe 2.0' ],
			[ 'Form factor', 'M.2 2280, single-sided' ],
			[ 'Sequential read', 'up to 7,400 MB/s' ],
			[ 'Sequential write', 'up to 6,500 MB/s' ],
			[ 'Controller / NAND', 'Maxio MAP1602, YMTC 232-layer TLC' ],
			[ 'Endurance', '1000 TBW' ],
			[ 'Location', 'M2_1 under the M.2 Shield Frozr heatsink' ],
		],
		note: 'Hidden under the heatsink — use the exploded view to lift the heatsink off.',
	},
	psu: {
		kicker: 'Power supply',
		name: 'Corsair RMe 750W (RM750e)',
		specs: [
			[ 'Output', '750 W continuous' ],
			[ 'Efficiency', '80 PLUS Gold, Cybenetics Gold' ],
			[ 'Standard', 'ATX 3.1, PCIe 5.1, native 12V-2x6' ],
			[ 'Modularity', 'Fully modular' ],
			[ 'Fan', '120 mm rifle bearing, Zero RPM mode' ],
			[ 'Dimensions', '150 × 86 × 140 mm' ],
			[ 'Location', 'Rear chamber of the H6 Flow' ],
		],
	},
	cooler: {
		kicker: 'CPU cooler',
		name: 'DeepCool LQ360 (white)',
		specs: [
			[ 'Type', '360 mm all-in-one liquid cooler' ],
			[ 'Radiator', '402 × 120 × 27 mm, aluminium' ],
			[ 'Pump', '89 × 76 × 64 mm, up to 3400 RPM' ],
			[ 'Display', 'Dashboard LCD, 53.9 × 49.15 mm' ],
			[ 'Fans', '3 × 120 mm ARGB, FDB' ],
			[ 'Tubing', '410 mm' ],
			[ 'Mounting', 'Top of case, fans exhausting upward' ],
		],
		note: 'Pump display shows simulated CPU temperature / load.',
	},
	case: {
		kicker: 'Case',
		name: 'NZXT H6 Flow (White)',
		specs: [
			[ 'Type', 'Dual-chamber mid-tower' ],
			[ 'Dimensions', '287 × 435 × 415 mm (W × H × D)' ],
			[ 'Panels', 'Wrap-around tempered glass front + left side' ],
			[ 'Included fans', '3 × 120 mm, angled front-right corner' ],
			[ 'Radiator support', 'Top up to 360 mm, rear 120 mm' ],
			[ 'Clearance', 'GPU 365 mm, CPU cooler 163 mm' ],
			[ 'Front I/O', 'USB-C, 2 × USB-A, audio combo' ],
		],
	},
	monitor: {
		kicker: 'Display',
		name: 'Xiaomi G Pro 27i',
		specs: [
			[ 'Panel', '27" Fast IPS, Mini LED backlight' ],
			[ 'Resolution / refresh', '2560 × 1440 @ 180 Hz' ],
			[ 'Local dimming', '1152 zones' ],
			[ 'Peak brightness', '1000 nits (HDR)' ],
			[ 'Response time', '1 ms GTG' ],
			[ 'Inputs', '2 × HDMI 2.0, 2 × DP 1.4' ],
			[ 'Desktop', 'Windows 11' ],
		],
	},
	keyboard: {
		kicker: 'Keyboard',
		name: 'AULA F75 Max',
		specs: [
			[ 'Layout', '75%, 80 keys + knob' ],
			[ 'Structure', 'Gasket mount, PC plate' ],
			[ 'Connectivity', 'USB-C, 2.4 GHz, Bluetooth' ],
			[ 'Display', '0.85" TFT screen' ],
			[ 'Battery', '4000 mAh' ],
			[ 'Lighting', 'South-facing RGB' ],
			[ 'Dimensions', '327.7 × 143.2 × 43.3 mm' ],
		],
		note: 'Exact colourway was not visible in the brief; modelled as white with light-grey modifiers.',
	},
	mouse: {
		kicker: 'Mouse',
		name: 'Logitech G502 LIGHTSPEED',
		specs: [
			[ 'Sensor', 'HERO 25K, 100–25,600 DPI' ],
			[ 'Connection', 'LIGHTSPEED 2.4 GHz wireless' ],
			[ 'Buttons', '11 programmable' ],
			[ 'Weight', '114 g (+ up to 16 g tuning weights)' ],
			[ 'Dimensions', '132 × 75 × 40 mm' ],
			[ 'Lighting', 'LIGHTSYNC RGB (logo, DPI indicator)' ],
		],
	},
};

export const PICKABLE_ORDER = [ 'case', 'motherboard', 'cpu', 'gpu', 'ram', 'cooler', 'ssd', 'psu', 'monitor', 'keyboard', 'mouse' ];
